baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "PaperCSS"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"

[privacy]
  [privacy.disqus]
    disable = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  navTitleLink = "/"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
