baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: PaperCSS
theme: papercss-hugo-theme
googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: A Hugo theme made with [PaperCSS](https://www.getpapercss.com/), the less formal CSS framework.
  homeMetaContent: A Hugo theme made with PaperCSS, the less formal CSS framework.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006

menu:
  nav:
    - name: Blog
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4
